#!/bin/bash

## Exports
export EDITOR=/usr/bin/vim


## Aliases && functions
# Redefine ls
alias ls='ls -lgGFhSt --color=auto'

# wifi-menu wrapper
alias wfm='sudo wifi-menu'

# launch xonotic-glx with sessionid
cozotic='xonotic-glx -sessionid cozy'

# a variable that makes installing from the AUR less annoying.
# and no I do not want yaourt
AUR='https://aur.archlinux.org'

## quicks for convienient editing

alias vfuncs='vim /home/cozy/script/funcs'



## Pacman wrapper & easy updater
get() {
	local cmd bwr npm pcm
	(($#)) || {echo "error: $?"; return "$?"}
	case $1 in
		in | install)  cmd=(sudo pacman -S --needed) ;;
		out | remove) cmd=(sudo pacman -Rds) ;;
		up | update )  cmd=(sudo pacman -Syyu);;
	esac
	$cmd $2

}


colors(){
	####### borrowed from tldp.com
	#   This file echoes a bunch of color codes to the 
	#   terminal to demonstrate what's available.  Each 
	#   line is the color code of one forground color,
	#   out of 17 (default + 16 escapes), followed by a 
	#   test use of that color on all nine background 
	#   colors (default + 8 escapes).
	#

	T='CZY'   # The test text
	
	echo -e "\n                 40m     41m     42m     43m\
	     44m     45m     46m     47m";
	
	for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
           '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
           '  36m' '1;36m' '  37m' '1;37m';
	  do FG=${FGs// /}
	  echo -en " $FGs \033[$FG  $T  "
	  for BG in 40m 41m 42m 43m 44m 45m 46m 47m;
	    do echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m";
	  done
	  echo;
	done
	echo

}


### Builds projects whose makefile is in common format.
ship() {

	((($#)) && [[ -f Makefile ]]) || return

	if [[ ! -r $1 ]] ;then	

		case $1 in
			clean) c=(sudo make clean) ;;
			it) c=(sudo make clean install);;
			*) c=(echo "please cat ~/script/funcs")
		esac
		$c
	else
		echo "$0 → invalid args " >&2

	fi
}



## Extract by file extension.
extract() {
#borrowed from the internet somewhere... 
#sorry! i dont even remember from where

    local c e i

    (($#)) || return

    for i; do
        c=''
        e=1

        if [[ ! -r $i ]]; then
            echo "$0: file is unreadable: \`$i'" >&2
            continue
        fi

        case $i in
            *.t@(gz|lz|xz|b@(2|z?(2))|a@(z|r?(.@(Z|bz?(2)|gz|lzma|xz)))))
                   c=(bsdtar xvf);;
            *.7z)  c=(7z x);;
            *.Z)   c=(uncompress);;
            *.bz2) c=(bunzip2);;
            *.exe) c=(cabextract);;
            *.gz)  c=(gunzip);;
            *.rar) c=(unrar x);;
            *.xz)  c=(unxz);;
            *.zip) c=(unzip);;
            *)     echo "$0: unrecognized file extension: \`$i'" >&2
                   continue;;
        esac

        command "${c[@]}" "$i"
        ((e = e || $?))
    done
    return "$e"
}



## go to a website.
ww() {
	local cmd
	(($#)) || return
	case $1 in
		ddg) cmd=(surf https://www.duckduckgo.com)  ;;
		ggl) cmd=(surf https://www.google.com)      ;;
		4cn) cmd=(surf htpps://www.4chan.org)       ;;
		  *) cmd=(echo "Get the fuck out of my ww");;	
	esac
	$cmd &

}
